# サイトの基本情報
title                      : "Portfolio"
description                : ""
url                        : "https://maan1231.github.io"

# スキンの変更（落ち着いた配色に設定）
minimal_mistakes_skin      : "air"

# プロフィール情報（サイドバーに表示されます）
author:
  name             : "眞鍋 光汰 (Kota Manabe)"
  bio              : "愛媛大学大学院 理工学研究科<br>数理情報プログラム 修士1年"
  location         : "愛媛県, 日本"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:manabe@ai.cs.ehime-u.ac.jp"
    - label: "Research Lab"
      icon: "fas fa-fw fa-link"
      url: "https://sites.google.com/view/ehime-nlp/"